processes:
  bkg:
    - top_2018
    - boson_2018
    #- Vfakeleps
    - Wjets_2018
    #- QCD
    #- ZInv

  sig:
    - SMS_TChiWZ
    - Cascades

sms_filters:
  - SMS_300_297
  - SMS_300_290
  - SMS_300_270
  - SMS_300_250
