processes:
  bkg:
    - top_FAKES
    - boson_FAKES
    - Wjets_FAKES

  sig:
    - Cascades
    - SMS_TChiWZ
    #- SMS_TChiWZ_Sandwich

sms_filters:
  - SMS_300_297
  - SMS_300_295
  - SMS_300_290
  - SMS_300_280
  - SMS_300_270
  - SMS_300_260
  - SMS_300_250
