processes:
  bkg:
    - top_Run2_FAKES
    - boson_Run2_FAKES
    - diboson_Run2_FAKES
    - triboson_Run2_FAKES
    - top_Run3_FAKES
    - boson_Run3_FAKES
    - diboson_Run3_FAKES
    - triboson_Run3_FAKES

  sig:
    - Cascades
    - SMS_TChiWZ
    - SMS_TChiWZpreUL
    - SMS_TChiWWpreUL
    - SMS_TSlepSleppreUL

sms_filters:
  - SMS_300_290
  - SMS_300_270
  - SMS_300_250
