bins:
  - name: "2L_Bronze_0J_Low_PTISR_Lowest_RISR"
    include:
        - "*2L_Bronze_0J_P250_R6_*"
        - "*2L_Bronze_0J_P250_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_0J_Low_PTISR_Low_RISR"
    include:
        - "*2L_Bronze_0J_P250_R7_*"
        - "*2L_Bronze_0J_P250_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_0J_Low_PTISR_Mid_RISR"
    include:
        - "*2L_Bronze_0J_P250_R8_*"
        - "*2L_Bronze_0J_P250_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_0J_Low_PTISR_High_RISR"
    include:
        - "*2L_Bronze_0J_P250_R9_*"
        - "*2L_Bronze_0J_P250_R95_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_Low_PTISR_Lowest_RISR"
    include:
        - "*2L_Bronze_1J_P250_R6_*"
        - "*2L_Bronze_1J_P250_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_Low_PTISR_Low_RISR"
    include:
        - "*2L_Bronze_1J_P250_R7_*"
        - "*2L_Bronze_1J_P250_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_Low_PTISR_Mid_RISR"
    include:
        - "*2L_Bronze_1J_P250_R8_*"
        - "*2L_Bronze_1J_P250_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_Low_PTISR_High_RISR"
    include:
        - "*2L_Bronze_1J_P250_R9_*"
        - "*2L_Bronze_1J_P250_R95_*"
    exclude:
        - "*Btag*"
  - name: "3L_Bronze_0J_Low_PTISR"
    include:
        - "*3L_Bronze_0J_P200_R6_*"
        - "*3L_Bronze_0J_P200_R7_*"
        - "*3L_Bronze_0J_P200_R8_*"
        - "*3L_Bronze_0J_P200_R9_*"
    exclude:
        - "*Btag*"
  - name: "3L_Bronze_0J_High_PTISR"
    include:
        - "*3L_Bronze_0J_P300_R6_*"
        - "*3L_Bronze_0J_P300_R7_*"
        - "*3L_Bronze_0J_P300_R8_*"
        - "*3L_Bronze_0J_P300_R9_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_0J_High_PTISR_Lowest_RISR"
    include:
        - "*2L_Bronze_0J_P350_R6_*"
        - "*2L_Bronze_0J_P350_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_0J_High_PTISR_Low_RISR"
    include:
        - "*2L_Bronze_0J_P350_R7_*"
        - "*2L_Bronze_0J_P350_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_0J_High_PTISR_Mid_RISR"
    include:
        - "*2L_Bronze_0J_P350_R8_*"
        - "*2L_Bronze_0J_P350_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_0J_High_PTISR_High_RISR"
    include:
        - "*2L_Bronze_0J_P350_R9_*"
        - "*2L_Bronze_0J_P350_R95_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_High_PTISR_Lowest_RISR"
    include:
        - "*2L_Bronze_1J_P350_R6_*"
        - "*2L_Bronze_1J_P350_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_High_PTISR_Low_RISR"
    include:
        - "*2L_Bronze_1J_P350_R7_*"
        - "*2L_Bronze_1J_P350_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_High_PTISR_Mid_RISR"
    include:
        - "*2L_Bronze_1J_P350_R8_*"
        - "*2L_Bronze_1J_P350_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Bronze_1J_High_PTISR_High_RISR"
    include:
        - "*2L_Bronze_1J_P350_R9_*"
        - "*2L_Bronze_1J_P350_R95_*"
    exclude:
        - "*Btag*"
  - name: "3L_Bronze_1J_Low_PTISR"
    include:
        - "*3L_Bronze_1J_P200_R6_*"
        - "*3L_Bronze_1J_P200_R7_*"
        - "*3L_Bronze_1J_P200_R8_*"
        - "*3L_Bronze_1J_P200_R9_*"
    exclude:
        - "*Btag*"
  - name: "3L_Bronze_1J_High_PTISR"
    include:
        - "*3L_Bronze_1J_P300_R6_*"
        - "*3L_Bronze_1J_P300_R7_*"
        - "*3L_Bronze_1J_P300_R8_*"
        - "*3L_Bronze_1J_P300_R9_*"
    exclude:
        - "*Btag*"
  - name: "4L_Bronze"
    include:
        "*4L_Bronze_*"
    exclude:
        - "*Btag*"
  - name: "Bronze_Btag"
    include:
        "*Bronze_*Btag"

  - name: "2L_Silver_0J_Low_PTISR_Lowest_RISR"
    include:
        - "*2L_Silver_0J_P250_R6_*"
        - "*2L_Silver_0J_P250_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_0J_Low_PTISR_Low_RISR"
    include:
        - "*2L_Silver_0J_P250_R7_*"
        - "*2L_Silver_0J_P250_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_0J_Low_PTISR_Mid_RISR"
    include:
        - "*2L_Silver_0J_P250_R8_*"
        - "*2L_Silver_0J_P250_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_0J_Low_PTISR_High_RISR"
    include:
        - "*2L_Silver_0J_P250_R9_*"
        - "*2L_Silver_0J_P250_R95_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_Low_PTISR_Lowest_RISR"
    include:
        - "*2L_Silver_1J_P250_R6_*"
        - "*2L_Silver_1J_P250_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_Low_PTISR_Low_RISR"
    include:
        - "*2L_Silver_1J_P250_R7_*"
        - "*2L_Silver_1J_P250_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_Low_PTISR_Mid_RISR"
    include:
        - "*2L_Silver_1J_P250_R8_*"
        - "*2L_Silver_1J_P250_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_Low_PTISR_High_RISR"
    include:
        - "*2L_Silver_1J_P250_R9_*"
        - "*2L_Silver_1J_P250_R95_*"
    exclude:
        - "*Btag*"
  - name: "3L_Silver_0J_Low_PTISR"
    include:
        - "*3L_Silver_0J_P200_R6_*"
        - "*3L_Silver_0J_P200_R7_*"
        - "*3L_Silver_0J_P200_R8_*"
        - "*3L_Silver_0J_P200_R9_*"
    exclude:
        - "*Btag*"
  - name: "3L_Silver_0J_High_PTISR"
    include:
        - "*3L_Silver_0J_P300_R6_*"
        - "*3L_Silver_0J_P300_R7_*"
        - "*3L_Silver_0J_P300_R8_*"
        - "*3L_Silver_0J_P300_R9_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_0J_High_PTISR_Lowest_RISR"
    include:
        - "*2L_Silver_0J_P350_R6_*"
        - "*2L_Silver_0J_P350_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_0J_High_PTISR_Low_RISR"
    include:
        - "*2L_Silver_0J_P350_R7_*"
        - "*2L_Silver_0J_P350_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_0J_High_PTISR_Mid_RISR"
    include:
        - "*2L_Silver_0J_P350_R8_*"
        - "*2L_Silver_0J_P350_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_0J_High_PTISR_High_RISR"
    include:
        - "*2L_Silver_0J_P350_R9_*"
        - "*2L_Silver_0J_P350_R95_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_High_PTISR_Lowest_RISR"
    include:
        - "*2L_Silver_1J_P350_R6_*"
        - "*2L_Silver_1J_P350_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_High_PTISR_Low_RISR"
    include:
        - "*2L_Silver_1J_P350_R7_*"
        - "*2L_Silver_1J_P350_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_High_PTISR_Mid_RISR"
    include:
        - "*2L_Silver_1J_P350_R8_*"
        - "*2L_Silver_1J_P350_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Silver_1J_High_PTISR_High_RISR"
    include:
        - "*2L_Silver_1J_P350_R9_*"
        - "*2L_Silver_1J_P350_R95_*"
    exclude:
        - "*Btag*"
  - name: "3L_Silver_1J_Low_PTISR"
    include:
        - "*3L_Silver_1J_P200_R6_*"
        - "*3L_Silver_1J_P200_R7_*"
        - "*3L_Silver_1J_P200_R8_*"
        - "*3L_Silver_1J_P200_R9_*"
    exclude:
        - "*Btag*"
  - name: "3L_Silver_1J_High_PTISR"
    include:
        - "*3L_Silver_1J_P300_R6_*"
        - "*3L_Silver_1J_P300_R7_*"
        - "*3L_Silver_1J_P300_R8_*"
        - "*3L_Silver_1J_P300_R9_*"
    exclude:
        - "*Btag*"
  - name: "4L_Silver"
    include:
        "*4L_Silver_*"
    exclude:
        - "*Btag*"
  - name: "Silver_Btag"
    include:
        "*Silver_*Btag"

  - name: "2L_Gold_0J_Low_PTISR_Lowest_RISR"
    include:
        - "*2L_Gold_0J_P250_R6_*"
        - "*2L_Gold_0J_P250_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_0J_Low_PTISR_Low_RISR"
    include:
        - "*2L_Gold_0J_P250_R7_*"
        - "*2L_Gold_0J_P250_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_0J_Low_PTISR_Mid_RISR"
    include:
        - "*2L_Gold_0J_P250_R8_*"
        - "*2L_Gold_0J_P250_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_0J_Low_PTISR_High_RISR"
    include:
        - "*2L_Gold_0J_P250_R9_*"
        - "*2L_Gold_0J_P250_R95_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_Low_PTISR_Lowest_RISR"
    include:
        - "*2L_Gold_1J_P250_R6_*"
        - "*2L_Gold_1J_P250_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_Low_PTISR_Low_RISR"
    include:
        - "*2L_Gold_1J_P250_R7_*"
        - "*2L_Gold_1J_P250_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_Low_PTISR_Mid_RISR"
    include:
        - "*2L_Gold_1J_P250_R8_*"
        - "*2L_Gold_1J_P250_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_Low_PTISR_High_RISR"
    include:
        - "*2L_Gold_1J_P250_R9_*"
        - "*2L_Gold_1J_P250_R95_*"
    exclude:
        - "*Btag*"
  - name: "3L_Gold_0J_Low_PTISR"
    include:
        - "*3L_Gold_0J_P200_R6_*"
        - "*3L_Gold_0J_P200_R7_*"
        - "*3L_Gold_0J_P200_R8_*"
        - "*3L_Gold_0J_P200_R9_*"
    exclude:
        - "*Btag*"
  - name: "3L_Gold_0J_High_PTISR"
    include:
        - "*3L_Gold_0J_P300_R6_*"
        - "*3L_Gold_0J_P300_R7_*"
        - "*3L_Gold_0J_P300_R8_*"
        - "*3L_Gold_0J_P300_R9_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_0J_High_PTISR_Lowest_RISR"
    include:
        - "*2L_Gold_0J_P350_R6_*"
        - "*2L_Gold_0J_P350_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_0J_High_PTISR_Low_RISR"
    include:
        - "*2L_Gold_0J_P350_R7_*"
        - "*2L_Gold_0J_P350_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_0J_High_PTISR_Mid_RISR"
    include:
        - "*2L_Gold_0J_P350_R8_*"
        - "*2L_Gold_0J_P350_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_0J_High_PTISR_High_RISR"
    include:
        - "*2L_Gold_0J_P350_R9_*"
        - "*2L_Gold_0J_P350_R95_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_High_PTISR_Lowest_RISR"
    include:
        - "*2L_Gold_1J_P350_R6_*"
        - "*2L_Gold_1J_P350_R65_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_High_PTISR_Low_RISR"
    include:
        - "*2L_Gold_1J_P350_R7_*"
        - "*2L_Gold_1J_P350_R75_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_High_PTISR_Mid_RISR"
    include:
        - "*2L_Gold_1J_P350_R8_*"
        - "*2L_Gold_1J_P350_R85_*"
    exclude:
        - "*Btag*"
  - name: "2L_Gold_1J_High_PTISR_High_RISR"
    include:
        - "*2L_Gold_1J_P350_R9_*"
        - "*2L_Gold_1J_P350_R95_*"
    exclude:
        - "*Btag*"
  - name: "3L_Gold_1J_Low_PTISR"
    include:
        - "*3L_Gold_1J_P200_R6_*"
        - "*3L_Gold_1J_P200_R7_*"
        - "*3L_Gold_1J_P200_R8_*"
        - "*3L_Gold_1J_P200_R9_*"
    exclude:
        - "*Btag*"
  - name: "3L_Gold_1J_High_PTISR"
    include:
        - "*3L_Gold_1J_P300_R6_*"
        - "*3L_Gold_1J_P300_R7_*"
        - "*3L_Gold_1J_P300_R8_*"
        - "*3L_Gold_1J_P300_R9_*"
    exclude:
        - "*Btag*"
  - name: "4L_Gold"
    include:
        "*4L_Gold_*"
    exclude:
        - "*Btag*"
  - name: "Gold_Btag"
    include:
        "*Gold_*Btag"

processes:
  merge:
    - name: "V_FAKES"
      include:
        #- "Vfakeleps*FAKES*"
        - "Vfakeleps*"
      #exclude:
      #  - "ST"
    - name: "Wjets"
      include:
        - "Wjet*"

    #- name: "top"
    #  include:
    #    - "top_2018*"

    #- name: "boson"
    #  include:
    #    - "boson_2018*"

    - name: "top_FAKES"
      include:
        - "top*FAKES*"

    - name: "top"
      include:
        - "top*"
      exclude:
        - "*FAKE*"

    - name: "boson_FAKES"
      include:
        - "boson*FAKES*"

    - name: "boson"
      include:
        - "boson*"
      exclude:
        - "*FAKE*"
