Bin2L_Gold_1J_P350_R9_Mh:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=35"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Mh:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=40;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R7_Mh:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=30;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# OSOF
Bin2L_Gold_1J_P350_R8_Mm_OS_emu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=20;Mperp_LEP<40"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSOF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Ml_OS_emu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSOF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R7_Ml_OS_emu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<30"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSOF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# OSSF ee
Bin2L_Gold_1J_P350_R9_Mm_OS_ee:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp>=20;Mperp_LEP<35;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Elec;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R9_Ml_OS_ee:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Elec;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Mm_OS_ee:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=20;Mperp_LEP<40;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Elec;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Ml_OS_ee:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Elec;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R7_Ml_OS_ee:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<30;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Elec;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# OSSF mumu
Bin2L_Gold_1J_P350_R9_Mm_OS_mumu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp>=20;Mperp_LEP<35;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Muon;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R9_Ml_OS_mumu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Muon;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Mm_OS_mumu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=20;Mperp_LEP<40;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Muon;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Ml_OS_mumu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Muon;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R7_Ml_OS_mumu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<30;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSSF;
    =2Muon;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# OSOF
Bin2L_Gold_1J_P350_R9_Mm_OS_emu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp>=20;Mperp_LEP<35;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSOF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R9_Ml_OS_emu:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    =1OSOF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# SS
Bin2L_Gold_1J_P350_R9_Mm_SS:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp>=20;Mperp_LEP<35;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    AllSS;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R9_Ml_SS:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    AllSS;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Mm_SS:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=20;Mperp_LEP<40;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    AllSS;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R8_Ml_SS:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<20;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    AllSS;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin2L_Gold_1J_P350_R7_Ml_SS:
  cuts: "Nlep==2;MET>=150;Njet>0;PTISR_LEP>=350;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<30;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =2Gold;
    AllSS;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
