Bin3L_Silver_1J_R9:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# Trying to split further with Q and F
Bin3L_Silver_0J_R9_Mh_Ah_OSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=30;MaRatio_LEP>=0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R9_Mh_Al_OSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=30;MaRatio_LEP<0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R9_Ml_Ah_OSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<30;MaRatio_LEP>=0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R9_Ml_Al_OSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<30;MaRatio_LEP<0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

Bin3L_Silver_0J_R9_Mh_Ah_nOSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=30;MaRatio_LEP>=0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =0OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R9_Mh_Al_nOSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=30;MaRatio_LEP<0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =0OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R9_Ml_Ah_nOSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<30;MaRatio_LEP>=0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =0OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R9_Ml_Al_nOSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<30;MaRatio_LEP<0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =0OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

Bin3L_Silver_1J_R8_Ml_Ah_SF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<40;MaRatio_LEP>=0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    AllSF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_1J_R8_Ml_Ah_OF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<40;MaRatio_LEP>=0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1Elec_a;
    =1Muon_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_1J_R7_Ml_OF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1Elec_a;
    =1Muon_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_1J_R8_Ml_Al_SF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<40;MaRatio_LEP<0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    AllSF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_1J_R7_Ml_SF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    AllSF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_1J_R8_Ml_Al_OF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP<40;MaRatio_LEP<0.3"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1Elec_a;
    =1Muon_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_1J_R8_Mh:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_1J_R7_Mh:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S>=1;Mperp_LEP>=40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# OSSF OSOF
Bin3L_Silver_0J_R8_Mh_OSSF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSSF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R7_Mh_OSSFa_OSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSSF_a;
    =1OSOF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R8_Ml_OSSFa_OSOF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSSF_a;
    =1OSOF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# OSSF AllSF
Bin3L_Silver_0J_R7_Mh_OSSFa_AllSF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSSF_a;
    AllSF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R8_Ml_OSSFa_AllSF:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSSF_a;
    AllSF;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# OS emu
Bin3L_Silver_0J_R8_Mh_OSOFa:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R7_Mh_OSOFa:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R8_Ml_OSOFa:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R7_Ml_OS:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<40;"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    =1Pos_a;
    =1Neg_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"

# SS
Bin3L_Silver_0J_R8_Mh_SS:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R7_Mh_SS:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP>=40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R8_Ml_SS:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin3L_Silver_0J_R7_Ml_SS:
  cuts: "Nlep==3;MET>=150;PTISR_LEP>=300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;MAX(abs(Eta_lep))<2.1;MIN(abs(Eta_lep))<1.4442;Nbjet==0;Njet_S==0;Mperp_LEP<40"
  lep-cuts: |
    >=1Silver;
    =0Bronze;
    =0OSSF|mass>=3|mass<=3.2;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
