Bin_Run3_4L_Bronze_R7_22:
  cuts: "Nlep==4;MET>=150;PTISR_LEP>=100;RISR_LEP>=0.7;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;Njet_S==0;MIN(abs(Eta_lep))<1.4442;Njet>0;Nlep_b_LEP==2;Nbjet==0;"
  lep-cuts: |
    >=1Gold;
    =2Bronze;
    =0OSSF|mass>=3|mass<=3.2;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run3_4L_Bronze_R7_31:
  cuts: "Nlep==4;MET>=150;PTISR_LEP>=100;RISR_LEP>=0.7;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;Njet_S==0;MIN(abs(Eta_lep))<1.4442;Njet>0;Nlep_b_LEP==1;Nbjet==0;"
  lep-cuts: |
    >=1Gold;
    =2Bronze;
    =0OSSF|mass>=3|mass<=3.2;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
