Bin_Run2_3L_Gold_Jincl_P200_R9_M30_OSOFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=30;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R9_M30_OSSFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=30;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSSF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R9_M30_SSa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=30;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R9_Mlt30_OSOFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<30;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R9_Mlt30_OSSFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<30;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSSF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R9_Mlt30_SSa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.9;RISR_LEP<=1.;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<30;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R8_M35_OSOFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=35;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R8_M35_OSSFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=35;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSSF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R8_M35_SSa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=35;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R8_Mlt35_OSOFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<35;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R8_Mlt35_OSSFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<35;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSSF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R8_Mlt35_SSa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.8;RISR_LEP<0.9;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<35;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R7_M40_OSOFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=40;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R7_M40_OSSFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=40;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSSF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R7_M40_SSa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP>=40;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R7_Mlt40_OSOFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<40;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSOF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R7_Mlt40_OSSFa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<40;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    =1OSSF_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
Bin_Run2_3L_Gold_Jincl_P200_R7_Mlt40_SSa:
  cuts: "Nlep==3;PTISR_LEP>=200;PTISR_LEP<300;RISR_LEP>=0.7;RISR_LEP<0.8;METORtrigger==1;EventFilter==1;PassesJVM==1;MIN(abs(Eta_lep))<1.4442;Njet>0;Mperp_LEP<40;Nbjet==0;MET>=150;"
  lep-cuts: |
    =0OSSF|mass>=3|mass<=3.2;
    =3Gold;
    AllSS_a;
  predefined-cuts: "Cleaning_LEP;dphiMETV_LEP;"
  user-cuts: "minMll_minDR_2D_low;HEM_Veto;leadSjet_pt;"
