manualExample1: # very basic
  cuts: "Nlep>=2;MET>=150;PTISR>=200"
  lep-cuts: ">=1OSSF"
  predefined-cuts: "Cleaning"

manualExample2: # loads of examples
  cuts: "Nlep>=3;MET>=100;PTISR>=100;MAX(SIP3D_lep)<4"
  lep-cuts: |
    #>=1Pos;
    >=1Mu;
    >=1Silver;
    >=1OSSF_a|mass![3.,3.2]|mass<65|DeltaR>0.4;
    >=1OSSF_b|mass![80,110]|DeltaR<0.5;
    >=1SSSF|mass>10
  predefined-cuts: "Cleaning;ZStar"

SuperBin2L: # Example SuperBin
  cuts: "Nlep==2;MET>=150;PTISR>=350;Nbjet==0;Mperp<=15;RISR>=0.95;RISR<=1;Njet_S==0"
  lep-cuts: |
    =2Gold;
    =1OSOF|mass![3.,3.2] # J/Psi Veto
  predefined-cuts: "Cleaning"
