#!/usr/bin/env python3
"""
checkJobsBF.py
Checks Condor job outputs for a given submission (condor/<submit_name>),
and, if there are failed jobs, writes a resubmit file for failed jobs.

Supports:
  - Multi-job submits using `queue LogFile, Args from (...)`
  - Single-job submits (just `queue 1`) as generated by make_submit_content()
"""
from __future__ import annotations
import argparse
import os
import re
import subprocess
import sys
import shutil
from typing import Dict, List, Tuple

CMS_ENV = "/cvmfs/cms.cern.ch/cmsset_default.sh"

def parse_args():
    p = argparse.ArgumentParser(description="Check and resubmit Condor jobs.")
    p.add_argument("submit_name", help="Name of the submission folder (e.g. manualExample1).")
    p.add_argument("--root-dir", default="condor", help="Top-level condor directory (default: 'condor').")
    p.add_argument("--no-submit", action="store_true", help="Do not actually call condor_submit; just write the resubmit file.")
    return p.parse_args()

def _file_nonzero(path: str) -> bool:
    return os.path.exists(path) and os.path.getsize(path) > 0

def _err_file_ok(err_path: str) -> Tuple[bool, List[str]]:
    if not os.path.exists(err_path):
        return True, []
    try:
        with open(err_path, "r", errors="ignore") as f:
            lines = [ln.rstrip("\n") for ln in f]
    except Exception:
        return True, []

    ignore_patterns = ["nvidia-drivers", "CUDA_COMPATIBILITY", "WARNING: In non-interactive mode release checks"]
    filtered = [ln for ln in lines if ln.strip() and not any(pat in ln for pat in ignore_patterns)]
    return len(filtered) == 0, filtered

def _out_file_ok(out_path: str) -> bool:
    if not os.path.exists(out_path):
        return False
    try:
        with open(out_path, "r", errors="ignore") as f:
            data = f.read()
    except Exception:
        return False
    return "Wrote datacard to: " in data

def check_job_ok(base_dir: str, job: str) -> bool:
    parent_dir = os.path.dirname(base_dir)
    signal = job.replace('job_','')
    datacard_path = os.path.join(parent_dir, "../datacards", job.replace('job_',''), f"{signal}.txt")
    out_path  = os.path.join(base_dir, f"{signal}.out")
    err_path  = os.path.join(base_dir, f"{signal}.err")
    file_ok = _file_nonzero(datacard_path)
    err_ok, err_lines = _err_file_ok(err_path)
    if not err_ok:
        print(f"[checkJobsBF] {err_path} has errors:", flush=True)
        for l in err_lines:
            print("   ", l, flush=True)
    out_ok = _out_file_ok(out_path)
    return file_ok and err_ok and out_ok

def parse_submit_for_mapping(submit_path: str) -> Tuple[str, Dict[str, str]]:
    """
    Parse multi-job submit files (queue LogFile, Args from (...)).
    Returns header and mapping {LogFile: Args}.
    """
    default_header = (
        "universe = vanilla\n"
        "executable = scripts/BF.sh\n"
        "should_transfer_files = YES\n"
        "when_to_transfer_output = ON_EXIT\n"
        "transfer_input_files = BF.x\n"
        "request_cpus = 1\n"
        "request_memory = 1 GB\n\n"
    )
    if not os.path.exists(submit_path):
        return default_header, {}

    try:
        with open(submit_path, "r", errors="ignore") as f:
            content = f.read()
    except Exception:
        return default_header, {}

    m = re.search(r'(.*?)(?:\r?\n)+queue\s+LogFile\s*,\s*Args\s+from\s*\(\s*(.*?)\s*\)', content, flags=re.S | re.I)
    mapping: Dict[str, str] = {}
    if m:
        header = m.group(1).rstrip() + "\n\n"
        queue_block = m.group(2)
        for line in queue_block.strip().splitlines():
            line = line.strip().rstrip(";")
            if not line or line.startswith("#"):
                continue
            mm = re.match(r'([^\s"\'=]+)\s+["\'](.+?)["\']\s*$', line)
            if mm:
                mapping[mm.group(1)] = mm.group(2)
            else:
                parts = line.split(None, 1)
                if len(parts) == 2:
                    mapping[parts[0]] = parts[1].strip().strip('"').strip("'")
        return header, mapping
    return default_header, {}

def write_resubmit_single_job(resubmit_path: str, orig_submit_path: str) -> None:
    """Copy a single-job submit to a resubmit file."""
    shutil.copyfile(orig_submit_path, resubmit_path)

def write_resubmit_multi_job(resubmit_path: str, header: str, mapping: Dict[str, str], failed_jobs: List[str]) -> None:
    """Write a multi-job submit with only failed jobs."""
    any_written = False
    with open(resubmit_path, "w") as rf:
        rf.write("# AUTO-GENERATED resubmit file\n")
        rf.write("# header (copied from original submit if available)\n")
        rf.write(header.rstrip() + "\n\n")
        rf.write("queue LogFile, Args from (\n")
        for j in failed_jobs:
            if j not in mapping:
                print(f"[checkJobsBF] Warning: job '{j}' not in original mapping; skipping.", file=sys.stderr)
                continue
            argstr = mapping[j].replace('"', '\\"')
            rf.write(f"{j} \"{argstr}\"\n")
            any_written = True
        rf.write(")\n")
    if not any_written:
        try:
            os.remove(resubmit_path)
        except Exception:
            pass
        raise RuntimeError("No failed jobs to resubmit.")

def main():
    args = parse_args()
    submit_name = args.submit_name
    base_dir = os.path.join(args.root_dir, submit_name)
    if not os.path.isdir(base_dir):
        print(f"[checkJobsBF] ERROR: {base_dir} not found.", file=sys.stderr)
        sys.exit(2)

    # Find submit files in base_dir (single-job style)
    submit_files = [f for f in os.listdir(base_dir) if f.endswith(".sub")]
    if not submit_files:
        print(f"[checkJobsBF] No .sub files found in {base_dir}.", file=sys.stderr)
        sys.exit(1)

    failed_jobs: List[str] = []

    for submit_file in submit_files:
        job_name = os.path.splitext(submit_file)[0]
        ok = check_job_ok(base_dir, job_name)
        if not ok:
            failed_jobs.append(job_name)

    if not failed_jobs:
        sys.exit(0)

    if len(failed_jobs) > 0:
        print(f"[checkJobsBF] Failed jobs ({len(failed_jobs)}):", flush=True)
    for j in failed_jobs:
        print("  ", j, flush=True)

    for job_name in failed_jobs:
        orig_submit_path = os.path.join(base_dir, f"{job_name}.sub")
        resubmit_path = os.path.join(base_dir, f"resubmit_{job_name}.sub")
        write_resubmit_single_job(resubmit_path, orig_submit_path)
        print(f"[checkJobsBF] Resubmit file written: {resubmit_path}", flush=True)

        if not args.no_submit:
            submit_cmd = f"source {CMS_ENV} && condor_submit {resubmit_path}"
            proc = subprocess.run(submit_cmd, shell=True, executable="/bin/bash", capture_output=True, text=True)
            if proc.returncode != 0:
                print(f"[checkJobsBF] condor_submit failed for {job_name}", file=sys.stderr)
                print(proc.stdout, file=sys.stderr)
                print(proc.stderr, file=sys.stderr)
            else:
                print(f"[checkJobsBF] Resubmit for {job_name} submitted successfully.", flush=True)

if __name__ == "__main__":
    main()

